### ISSUE TITLE
Links in Atom's markdown preview aren't highlighted 

### ISSUE THREAD

**Issue by rafgraph** [tpoisot/writer-syntax#7]
It would be nice to have some differentiation of what's a link when using Atom's markdown preview.

**Comment by rafgraph** [comment]
Setting global styles to what's below does the trick. It'd be nice if you incorporated it into the theme.

``` css
.markdown-preview a {
  text-decoration: underline;
}
```
